
# We want Exclude directives merged, not overwritten
inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop_strict.yml

RSpec/ExampleLength:
  Exclude:
    - "spec/utterson/base_spec.rb"

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
